image: node:6.17.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
    - git config --global url.https://github.com/.insteadOf git://github.com/ # fixes https://github.com/nodejs/help/issues/1461
    - cd oTranscribe
    - apt-get install -y make
    - npm i
    - make build_prod
    - mv dist ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

